name: Update SuperLiga Scores
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: node .github/scripts/fetch_scores.mjs
      - name: Push Changes
        run: |
          git config --global user.name "ScoreBot"
          git config --global user.email "bot@github.com"
          git add data/superliga.json
          git commit -m "Update scores [skip ci]" || exit 0
          git push
