      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Verificăm dacă fișierul a fost creat de script
          if [ -f data/superliga.json ]; then
            git add data/superliga.json
            if git diff --cached --quiet; then
              echo "Nicio schimbare de conținut."
            else
              git commit -m "Update scores [skip ci]"
              git push origin main
            fi
          else
            echo "Fișierul superliga.json nu a fost găsit. Sărim peste commit."
          fi
