name: Update SuperLiga Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # AM MODIFICAT AICI: De la 20 la 24
          node-version: '24'

      - name: Install dependencies
        run: npm install cheerio

      - name: Run Standings Scraper
        run: node .github/scripts/fetch_standings.mjs

      - name: Run Matches Fetcher
        run: node .github/scripts/fetch_matches.mjs
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/superliga.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scores and standings [skip ci]" && git push)
